# Generated by Django 6.0.2 on 2026-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionUploadTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session Key')),
                ('student_name', models.CharField(blank=True, max_length=100, verbose_name='Student Name')),
                ('student_surname', models.CharField(blank=True, max_length=100, verbose_name='Student Surname')),
                ('school_id', models.CharField(blank=True, max_length=50, verbose_name='School ID')),
                ('variant', models.CharField(blank=True, max_length=50, verbose_name='Variant')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='School Name (Matched)')),
                ('school_status', models.CharField(default='Not Found', max_length=50, verbose_name='School Match Status')),
                ('answers_count', models.IntegerField(default=0, verbose_name='Answers Count')),
                ('answers_raw', models.JSONField(blank=True, default=dict, verbose_name='Raw Answers (JSON)')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Percentage')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('status', models.CharField(default='valid', max_length=50, verbose_name='Processing Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission Upload Temp',
                'verbose_name_plural': 'Admission Upload Temps',
                'ordering': ['id'],
            },
        ),
    ]
