# Generated by Django 6.0.2 on 2026-03-29 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('exams', '0008_onlineexam_enable_recording'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('previous_school', models.CharField(max_length=255, verbose_name='Previous School')),
                ('grade_applying_for', models.CharField(max_length=10, verbose_name='Grade Applying For')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admission Candidate',
                'verbose_name_plural': 'Admission Candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cycle Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_cycles', to='exams.onlineexam', verbose_name='Admission Exam')),
            ],
            options={
                'verbose_name': 'Admission Cycle',
                'verbose_name_plural': 'Admission Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='AdmissionUploadTemp',
        ),
        migrations.AddField(
            model_name='admissioncandidate',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='admissions.admissioncycle', verbose_name='Admission Cycle'),
        ),
    ]
