# Generated by Django 6.0.2 on 2026-03-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissioncandidate_admissioncycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('school_id', models.CharField(max_length=50, unique=True, verbose_name='School ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External School',
                'verbose_name_plural': 'External Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='admissioncandidate',
            name='previous_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='admissions.externalschool', verbose_name='Previous School'),
        ),
    ]
