# Generated by Django 6.0.2 on 2026-03-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_externalschool_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omr_sessions', to='admissions.admissioncycle', verbose_name='Admission Cycle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'OMR Analysis Session',
                'verbose_name_plural': 'OMR Analysis Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OMRStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_first_name', models.CharField(max_length=100, verbose_name='Raw First Name')),
                ('raw_last_name', models.CharField(max_length=100, verbose_name='Raw Last Name')),
                ('raw_school_id', models.CharField(max_length=50, verbose_name='Raw School ID')),
                ('raw_student_id', models.CharField(max_length=50, verbose_name='Raw Student ID')),
                ('variant', models.CharField(max_length=10, verbose_name='Variant')),
                ('student_answers', models.TextField(verbose_name='Student Answers')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Is Matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omr_results', to='admissions.admissioncandidate', verbose_name='Candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admissions.omranalysissession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'OMR Student Result',
                'verbose_name_plural': 'OMR Student Results',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='OMRMasterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('1A', '1A'), ('1B', '1B (1Б)'), ('2A', '2A'), ('2B', '2B (2Б)')], max_length=10, verbose_name='Variant')),
                ('answers', models.TextField(verbose_name='Correct Answers')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_keys', to='admissions.omranalysissession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'OMR Master Key',
                'verbose_name_plural': 'OMR Master Keys',
                'unique_together': {('session', 'variant')},
            },
        ),
    ]
