# Generated by Django 6.0.2 on 2026-03-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_omranalysissession_omrstudentresult_omrmasterkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omranalysissession',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='omranalysissession',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='omrstudentresult',
            name='session',
        ),
        migrations.RemoveField(
            model_name='omrstudentresult',
            name='candidate',
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, help_text='Minimum percentage required to pass for this cycle.', verbose_name='Passing Score (%)'),
        ),
        migrations.DeleteModel(
            name='OMRMasterKey',
        ),
        migrations.DeleteModel(
            name='OMRAnalysisSession',
        ),
        migrations.DeleteModel(
            name='OMRStudentResult',
        ),
    ]
