# Generated by Django 6.0.2 on 2026-03-30 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_remove_omranalysissession_cycle_and_more'),
        ('exams', '0009_onlineexam_enable_proctoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('admission_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20, verbose_name='Admission Type')),
                ('file', models.FileField(upload_to='admission_uploads/', verbose_name='XLSX File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='admissions.admissioncycle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Upload Session',
                'verbose_name_plural': 'Admission Upload Sessions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('score', models.FloatField(verbose_name='Score')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Is Passed')),
                ('admission_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20, verbose_name='Admission Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_results', to='admissions.admissioncandidate')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admissions.admissioncycle')),
                ('exam_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_result', to='exams.examattempt')),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admissions.admissionuploadsession')),
            ],
            options={
                'verbose_name': 'Admission Result',
                'verbose_name_plural': 'Admission Results',
                'ordering': ['-score'],
            },
        ),
    ]
