# Generated by Django 6.0.2 on 2026-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admissionuploadsession_admissionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='phone1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2'),
        ),
    ]
