# Generated by Django 6.0.2 on 2026-03-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_admissionresult_phone1_admissionresult_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='overall_wrong',
            field=models.IntegerField(default=0, verbose_name='Overall Wrong'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='raw_answers',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Answers'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='subject_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Subject Data'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='variant_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Variant'),
        ),
        migrations.CreateModel(
            name='AdmissionMasterAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=10, verbose_name='Variant')),
                ('answers', models.CharField(max_length=200, verbose_name='Answer Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_answers', to='admissions.admissioncycle')),
            ],
            options={
                'verbose_name': 'Admission Master Answer',
                'verbose_name_plural': 'Admission Master Answers',
                'unique_together': {('cycle', 'variant')},
            },
        ),
    ]
