# Generated by Django 6.0.2 on 2026-03-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_admissionresult_overall_wrong_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionmasteranswer',
            options={'verbose_name': 'Master Answer', 'verbose_name_plural': 'Master Answers'},
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='overall_wrong',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='raw_answers',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='subject_data',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='answer_string',
            field=models.TextField(blank=True, default='', verbose_name='Raw Answer String'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='correct_count',
            field=models.IntegerField(default=0, verbose_name='Correct Answers'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='variant',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B')], default='', max_length=5, verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='Wrong Answers'),
        ),
        migrations.AlterField(
            model_name='admissionmasteranswer',
            name='answers',
            field=models.TextField(help_text='Enter the 70-character answer key string. E.g. АБВГАБВГ...', verbose_name='Answer Key (70 characters)'),
        ),
        migrations.AlterField(
            model_name='admissionmasteranswer',
            name='variant',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B')], max_length=5, verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='total_questions',
            field=models.IntegerField(default=70, verbose_name='Total Questions'),
        ),
        migrations.CreateModel(
            name='AdmissionSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Wrong Answers')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total Questions')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='admissions.admissionresult')),
            ],
            options={
                'verbose_name': 'Subject Score',
                'verbose_name_plural': 'Subject Scores',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSubjectSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B')], max_length=5, verbose_name='Variant')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('start_question', models.PositiveIntegerField(verbose_name='Start Question (1-indexed)')),
                ('end_question', models.PositiveIntegerField(verbose_name='End Question (1-indexed, inclusive)')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_splits', to='admissions.admissioncycle')),
            ],
            options={
                'verbose_name': 'Subject Split',
                'verbose_name_plural': 'Subject Splits',
                'ordering': ['variant', 'start_question'],
            },
        ),
    ]
