# Generated by Django 6.0.2 on 2026-03-30 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_admissionmasteranswer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name (ФИО)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('phone1', models.CharField(max_length=50, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 2')),
                ('variant', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B')], max_length=5, verbose_name='Variant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='admissions.admissioncycle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Admission Registration',
                'verbose_name_plural': 'Admission Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
