# Generated by Django 6.0.2 on 2026-04-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_admissionregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissioncycle',
            name='exam',
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='enable_tab_warnings',
            field=models.BooleanField(default=True, help_text='If disabled, students can switch tabs without warnings.', verbose_name='Enable Tab Switch Warnings'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='max_tab_switches',
            field=models.PositiveIntegerField(default=3, verbose_name='Max Tab Switches Before Lock'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='timer_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of the online admission exam.', verbose_name='Timer (minutes)'),
        ),
        migrations.CreateModel(
            name='AdmissionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='admission_questions/', verbose_name='Question Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admissions.admissioncycle', verbose_name='Admission Cycle')),
            ],
            options={
                'verbose_name': 'Admission Question',
                'verbose_name_plural': 'Admission Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='admissions.admissionquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Admission Question Option',
                'verbose_name_plural': 'Admission Question Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnlineAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('locked', 'Locked'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20, verbose_name='Status')),
                ('tab_switch_count', models.PositiveIntegerField(default=0, verbose_name='Tab Switch Count')),
                ('lock_reason', models.CharField(blank=True, max_length=200, verbose_name='Lock Reason')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_attempts', to='admissions.admissioncycle', verbose_name='Admission Cycle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_admission_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Online Exam Attempt',
                'verbose_name_plural': 'Online Exam Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('cycle', 'student')},
            },
        ),
        migrations.CreateModel(
            name='OnlineAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Answered At')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admissions.onlineattempt', verbose_name='Attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='admissions.admissionquestion', verbose_name='Question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='admissions.admissionquestionoption', verbose_name='Selected Option')),
            ],
            options={
                'verbose_name': 'Online Attempt Answer',
                'verbose_name_plural': 'Online Attempt Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
