# Generated by Django 6.0.2 on 2026-04-04 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_remove_admissioncycle_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='student_user',
            field=models.ForeignKey(blank=True, help_text='For online attempts directly tied to a user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_results_direct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionquestion',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_questions', to='admissions.admissioncycle', verbose_name='Admission Cycle'),
        ),
    ]
