# Generated by Django 6.0.2 on 2026-04-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_admissionresult_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionresult',
            name='student_user',
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='exam_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_result', to='admissions.onlineattempt'),
        ),
        migrations.AlterField(
            model_name='onlineattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20, verbose_name='Status'),
        ),
    ]
