# Generated by Django 6.0.2 on 2026-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_remove_admissionresult_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncandidate',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='admissioncandidate',
            name='grade_applying_for',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Grade Applying For'),
        ),
    ]
