# Generated by Django 6.0.2 on 2026-04-08 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_alter_admissioncandidate_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(upload_to='round_results/', verbose_name='Excel File')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Round Result Session',
                'verbose_name_plural': 'Round Result Sessions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Full Name')),
                ('biology_score', models.FloatField(blank=True, null=True, verbose_name='Biology Score')),
                ('biology_pct', models.FloatField(blank=True, null=True, verbose_name='Biology %')),
                ('math_score', models.FloatField(blank=True, null=True, verbose_name='Math Score')),
                ('math_pct', models.FloatField(blank=True, null=True, verbose_name='Math %')),
                ('english_score', models.FloatField(blank=True, null=True, verbose_name='English Score')),
                ('english_pct', models.FloatField(blank=True, null=True, verbose_name='English %')),
                ('total_score', models.FloatField(default=0, verbose_name='Total Score')),
                ('total_pct', models.FloatField(default=0, verbose_name='Total %')),
                ('status', models.CharField(choices=[('accepted', 'кабыл алынган'), ('rejected', 'кабыл алынбаган')], default='rejected', max_length=20, verbose_name='Status')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admissions.roundresultsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Round Result',
                'verbose_name_plural': 'Round Results',
                'ordering': ['-total_score'],
            },
        ),
    ]
