# Generated by Django 6.0.2 on 2026-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_roundresultsession_roundresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='district',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='geography_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Geography %'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='geography_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Geography Score'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='history_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='History %'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='history_score',
            field=models.FloatField(blank=True, null=True, verbose_name='History Score'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='kyrgyz_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Kyrgyz %'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='kyrgyz_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Kyrgyz Score'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='medal',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Medal'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='russian_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Russian %'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='russian_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Russian Score'),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='school',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='School'),
        ),
    ]
