# Generated by Django 6.0.2 on 2026-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_roundresult_district_roundresult_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresultsession',
            name='passing_score',
            field=models.FloatField(default=24.0, verbose_name='Passing Score Threshold'),
        ),
        migrations.AlterField(
            model_name='roundresult',
            name='status',
            field=models.CharField(choices=[('accepted', 'Өттү'), ('rejected', 'Өтпөдү')], default='rejected', max_length=20, verbose_name='Status'),
        ),
    ]
