# Generated by Django 6.0.2 on 2026-04-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_roundresultsession_passing_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Link Title')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='admissions.admissioncycle', verbose_name='Cycle')),
            ],
            options={
                'verbose_name': 'Cycle Link',
                'verbose_name_plural': 'Cycle Links',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
