# Generated by Django 6.0.2 on 2026-04-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclelink',
            name='target_gender',
            field=models.CharField(choices=[('all', 'All'), ('M', 'Boys'), ('F', 'Girls')], default='all', max_length=5, verbose_name='Target Gender'),
        ),
    ]
