# Generated by Django 6.0.2 on 2026-04-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_cyclelink_target_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncycle',
            name='enable_anti_copy',
            field=models.BooleanField(default=True, help_text='Block copy/paste, right-click, and keyboard shortcuts during exam.', verbose_name='Enable Anti-Copy Protection'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='enable_movement_detection',
            field=models.BooleanField(default=False, help_text='If enabled, periodic snapshots are sent for proctoring analysis.', verbose_name='Enable Suspicious Movement Detection'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='require_webcam',
            field=models.BooleanField(default=False, help_text='If enabled, students must allow camera access before starting.', verbose_name='Require Webcam Recording'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='tab_switch_action',
            field=models.CharField(choices=[('warn_only', 'Warn Only'), ('auto_submit', 'Auto-Submit Exam'), ('mark_suspicious', 'Mark as Suspicious')], default='auto_submit', help_text='What happens when a student exceeds the tab switch limit.', max_length=20, verbose_name='Action on Tab Limit'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='copy_paste_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Copy/Paste Violation Count'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Flagged as Suspicious'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='right_click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Right-Click Count'),
        ),
        migrations.CreateModel(
            name='ExamRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='exam_recordings/%Y/%m/', verbose_name='Video File')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Recording Started')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Recording Ended')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='admissions.onlineattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Exam Recording',
                'verbose_name_plural': 'Exam Recordings',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy', 'Copy Attempt'), ('paste', 'Paste Attempt'), ('right_click', 'Right-Click'), ('shortcut', 'Blocked Shortcut'), ('camera_denied', 'Camera Permission Denied'), ('camera_lost', 'Camera Lost During Exam')], max_length=30, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.TextField(blank=True, default='', verbose_name='Details')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_logs', to='admissions.onlineattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Exam Violation Log',
                'verbose_name_plural': 'Exam Violation Logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('face_not_visible', 'Face Not Visible'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('camera_blocked', 'Camera Blocked'), ('other', 'Other')], max_length=30, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Confidence')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='proctoring_snapshots/%Y/%m/', verbose_name='Snapshot')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='admissions.onlineattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Proctoring Event',
                'verbose_name_plural': 'Proctoring Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
