# Generated by Django 6.0.2 on 2026-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_admissioncycle_enable_anti_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished At'),
        ),
        migrations.AlterField(
            model_name='examviolationlog',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy', 'Copy Attempt'), ('paste', 'Paste Attempt'), ('right_click', 'Right-Click'), ('shortcut', 'Blocked Shortcut'), ('movement', 'Suspicious Movement'), ('camera_denied', 'Camera Permission Denied'), ('camera_lost', 'Camera Lost During Exam')], max_length=30, verbose_name='Event Type'),
        ),
    ]
