# Generated by Django 6.0.2 on 2026-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_onlineattempt_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncycle',
            name='prevent_back_navigation',
            field=models.BooleanField(default=False, help_text='If enabled, students cannot return to previous questions after answering.', verbose_name='Prevent Previous Question'),
        ),
    ]
