# Generated by Django 6.0.2 on 2026-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_admissioncycle_prevent_back_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionquestion',
            name='is_survey_question',
            field=models.BooleanField(default=False, verbose_name='Is Survey (No points, appears first)'),
        ),
    ]
