# Generated by Django 6.0.2 on 2026-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_admissionquestion_is_survey_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringevent',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='admissioncycle',
            name='enable_anti_copy',
        ),
        migrations.RemoveField(
            model_name='admissioncycle',
            name='enable_movement_detection',
        ),
        migrations.RemoveField(
            model_name='admissioncycle',
            name='enable_tab_warnings',
        ),
        migrations.RemoveField(
            model_name='admissioncycle',
            name='max_tab_switches',
        ),
        migrations.RemoveField(
            model_name='admissioncycle',
            name='tab_switch_action',
        ),
        migrations.RemoveField(
            model_name='onlineattempt',
            name='copy_paste_count',
        ),
        migrations.RemoveField(
            model_name='onlineattempt',
            name='is_suspicious',
        ),
        migrations.RemoveField(
            model_name='onlineattempt',
            name='lock_reason',
        ),
        migrations.RemoveField(
            model_name='onlineattempt',
            name='right_click_count',
        ),
        migrations.RemoveField(
            model_name='onlineattempt',
            name='tab_switch_count',
        ),
        migrations.DeleteModel(
            name='ExamViolationLog',
        ),
        migrations.DeleteModel(
            name='ProctoringEvent',
        ),
    ]
