# Generated by Django 6.0.2 on 2026-04-25 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_remove_proctoringevent_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncycle',
            name='enable_tab_warnings',
            field=models.BooleanField(default=False, help_text='If enabled, students will be warned when switching tabs.', verbose_name='Enable Tab Switch Warnings'),
        ),
        migrations.AddField(
            model_name='admissioncycle',
            name='max_tab_switches',
            field=models.PositiveIntegerField(default=3, help_text='Number of tab switches allowed before blocking the exam.', verbose_name='Max Tab Switches'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tab Switch Warnings'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='lock_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lock Reason'),
        ),
        migrations.AddField(
            model_name='onlineattempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tab Switch Warnings'),
        ),
        migrations.CreateModel(
            name='OnlineExamViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('camera_denied', 'Camera Denied'), ('camera_lost', 'Camera Lost'), ('other', 'Other')], max_length=50, verbose_name='Event Type')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='admissions.onlineattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Exam Violation',
                'verbose_name_plural': 'Exam Violations',
                'ordering': ['timestamp'],
            },
        ),
    ]
