# Generated by Django 6.0.2 on 2026-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0026_admissioncycle_enable_tab_warnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='exam_duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Exam Duration (seconds)'),
        ),
    ]
