# Generated by Django 6.0.2 on 2026-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_admissionresult_exam_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncycle',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='e.g., 1 for First Round, 2 for Second Round.', verbose_name='Round Number'),
        ),
    ]
