# Generated by Django 6.0.2 on 2026-04-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0003_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Generated Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.schoolclass', verbose_name='Class'),
        ),
    ]
