# Generated by Django 6.0.2 on 2026-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plain_password_user_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('internal', 'Student Aalam'), ('applicant', 'Admission Student')], default='internal', help_text='Internal = class-managed school student, Applicant = admission registrant', max_length=20, verbose_name='Student Type'),
        ),
    ]
