# Generated by Django 6.0.1 on 2026-01-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='Passing Score (%)')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Shuffle Questions')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='Shuffle Options')),
                ('show_results_immediately', models.BooleanField(default=True, verbose_name='Show Results Immediately')),
                ('max_tab_switches', models.PositiveIntegerField(default=3, verbose_name='Max Tab Switches Before Lock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='schools.school', verbose_name='School')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='schools.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Online Exam',
                'verbose_name_plural': 'Online Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='exam_questions/', verbose_name='Question Image')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20, verbose_name='Question Type')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.onlineexam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('locked', 'Locked'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20, verbose_name='Status')),
                ('tab_switch_count', models.PositiveIntegerField(default=0, verbose_name='Tab Switch Count')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('lock_reason', models.CharField(blank=True, max_length=200, verbose_name='Lock Reason')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.onlineexam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('window_blur', 'Window Blur'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('exam_locked', 'Exam Locked'), ('admin_unlock', 'Admin Unlock'), ('exam_started', 'Exam Started'), ('exam_submitted', 'Exam Submitted')], max_length=30, verbose_name='Event Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='exams.examattempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Proctor Event',
                'verbose_name_plural': 'Proctor Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.examquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Answered At')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt', verbose_name='Attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='exams.examquestion', verbose_name='Question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='exams.questionoption', verbose_name='Selected Option')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
