# Generated by Django 6.0.1 on 2026-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Text Answer'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct_answers',
            field=models.TextField(blank=True, help_text='For fill-in-the-blanks: separate multiple correct variants with | (pipe)', verbose_name='Correct Answers'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks')], default='multiple_choice', max_length=20, verbose_name='Question Type'),
        ),
    ]
