# Generated by Django 6.0.2 on 2026-02-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_attemptanswer_text_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='matching_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Matching Answers'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching')], default='multiple_choice', max_length=20, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='onlineexam',
            name='show_results_immediately',
            field=models.BooleanField(default=False, verbose_name='Show Results Immediately'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=500, verbose_name='Left Item (Column A)')),
                ('right_item', models.CharField(max_length=500, verbose_name='Right Item (Column B)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='exams.examquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Matching Pair',
                'verbose_name_plural': 'Matching Pairs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
