# Generated by Django 6.0.2 on 2026-03-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_matching_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='ordering_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ordering Answers'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct_answer_boolean',
            field=models.BooleanField(blank=True, help_text='For True/False questions: select the correct answer', null=True, verbose_name='Correct Answer (True/False)'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blanks', 'Fill in the Blanks'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('true_false', 'True / False')], default='multiple_choice', max_length=20, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Item Text')),
                ('correct_position', models.PositiveIntegerField(default=0, verbose_name='Correct Position')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='exams.examquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Ordering Item',
                'verbose_name_plural': 'Ordering Items',
                'ordering': ['correct_position', 'id'],
            },
        ),
    ]
