# Generated by Django 6.0.2 on 2026-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_attemptanswer_ordering_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='partial_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Partial Score'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Score'),
        ),
    ]
