# Generated by Django 6.0.2 on 2026-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_attemptanswer_partial_score_alter_examattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexam',
            name='prevent_go_back',
            field=models.BooleanField(default=False, verbose_name='Prevent Returning to Previous Questions'),
        ),
    ]
