# Generated by Django 6.0.2 on 2026-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_onlineexam_prevent_go_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='exam_recordings/', verbose_name='Exam Recording'),
        ),
    ]
