# Generated by Django 6.0.2 on 2026-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examattempt_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexam',
            name='enable_recording',
            field=models.BooleanField(default=False, verbose_name='Enable Video Recording'),
        ),
    ]
