# Generated by Django 6.0.2 on 2026-03-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_onlineexam_enable_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexam',
            name='enable_proctoring',
            field=models.BooleanField(default=True, verbose_name='Enable Proctoring (Tab/Blur Detection)'),
        ),
    ]
