# Generated by Django 6.0.2 on 2026-04-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_onlineexam_enable_proctoring'),
        ('schools', '0003_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineexam',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Select specific classes or leave empty for all students', related_name='assigned_exams', to='schools.schoolclass', verbose_name='Target Classes'),
        ),
    ]
