server {
    listen 80;
    server_name aalam-synak.edu.kg www.aalam-synak.edu.kg;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /home/ubuntu/Aalam-Synak;
    }

    location /media/ {
        root /home/ubuntu/Aalam-Synak;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/Aalam-Synak/aalam.sock;
    }
}
