# Generated by Django 6.0.1 on 2026-01-27 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipGradeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Exam Title')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total Students')),
                ('unknown_students', models.PositiveIntegerField(default=0, verbose_name='Unknown Students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipgrade_exams', to='schools.school', verbose_name='School')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exams', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'ZipGrade Exam',
                'verbose_name_plural': 'ZipGrade Exams',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_question', models.PositiveIntegerField(verbose_name='Start Question')),
                ('end_question', models.PositiveIntegerField(verbose_name='End Question')),
                ('points_per_question', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Points per Question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_splits', to='schools.subject', verbose_name='Subject')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_splits', to='zipgrade.zipgradeexam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Subject Split',
                'verbose_name_plural': 'Subject Splits',
                'ordering': ['start_question'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipgrade_student_id', models.CharField(max_length=50, verbose_name='ZipGrade Student ID')),
                ('zipgrade_first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name (ZipGrade)')),
                ('zipgrade_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name (ZipGrade)')),
                ('earned_points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Earned Points')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Max Points')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage')),
                ('answers', models.TextField(blank=True, verbose_name='Answers (JSON)')),
                ('is_unknown', models.BooleanField(default=False, verbose_name='Unknown Student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', to='schools.masterstudent', verbose_name='Student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='zipgrade.zipgradeexam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-percentage'],
                'unique_together': {('exam', 'zipgrade_student_id')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Earned Points')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Max Points')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage')),
                ('question_results', models.TextField(blank=True, verbose_name='Question Results (JSON)')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='zipgrade.examresult', verbose_name='Result')),
                ('subject_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='zipgrade.subjectsplit', verbose_name='Subject Split')),
            ],
            options={
                'verbose_name': 'Subject Result',
                'verbose_name_plural': 'Subject Results',
                'unique_together': {('result', 'subject_split')},
            },
        ),
    ]
