# Generated by Django 6.0.1 on 2026-01-30 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_logo'),
        ('zipgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='manual_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manual First Name'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='manual_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manual Last Name'),
        ),
        migrations.CreateModel(
            name='ExamFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Folder Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='zipgrade.examfolder', verbose_name='Parent Folder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_folders', to='schools.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Exam Folder',
                'verbose_name_plural': 'Exam Folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='zipgradeexam',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='zipgrade.examfolder', verbose_name='Folder'),
        ),
    ]
