# Generated by Django 6.0.1 on 2026-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipgrade', '0002_examresult_manual_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='manual_class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Manual Class Name'),
        ),
    ]
