# Generated by Django 6.0.1 on 2026-02-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipgrade', '0003_examresult_manual_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectsplit',
            unique_together=set(),
        ),
    ]
