# Generated by Django 6.0.1 on 2026-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipgrade', '0004_alter_subjectsplit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipgradeexam',
            name='answer_key',
            field=models.TextField(blank=True, verbose_name='Answer Key (JSON)'),
        ),
    ]
