# Generated by Django 6.0.2 on 2026-04-07 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cycle Name')),
                ('passing_threshold', models.FloatField(default=60.0, verbose_name='Passing Threshold (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Olympiad Cycle',
                'verbose_name_plural': 'Olympiad Cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name (ФИО)')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('school', models.CharField(max_length=255, verbose_name='School')),
                ('phone1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('total_score', models.FloatField(verbose_name='Total Score')),
                ('percentage', models.FloatField(verbose_name='Percentage')),
                ('medal', models.CharField(blank=True, max_length=50, verbose_name='Medal')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='olympiad.olympiadcycle')),
            ],
            options={
                'verbose_name': 'Olympiad Result',
                'verbose_name_plural': 'Olympiad Results',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadSubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('score_display', models.CharField(max_length=100, verbose_name='Score Display')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='olympiad.olympiadresult')),
            ],
            options={
                'verbose_name': 'Subject Score',
                'verbose_name_plural': 'Subject Scores',
            },
        ),
        migrations.CreateModel(
            name='OlympiadUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='olympiad_uploads/', verbose_name='Excel File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='olympiad.olympiadcycle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
            },
        ),
        migrations.AddField(
            model_name='olympiadresult',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='olympiad.olympiaduploadsession'),
        ),
    ]
