# Generated by Django 6.0.2 on 2026-04-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiadcycle',
            options={'ordering': ['-created_at'], 'verbose_name': '1-Кабыл алуу жыйынтыктары', 'verbose_name_plural': '1-Кабыл алуу жыйынтыктары'},
        ),
        migrations.AlterModelOptions(
            name='olympiadresult',
            options={'ordering': ['-total_score'], 'verbose_name': '1-Кабыл алуу жыйытныгы', 'verbose_name_plural': '1-Кабыл алуу жыйынтыктары'},
        ),
        migrations.AddField(
            model_name='olympiadsubjectscore',
            name='numeric_score',
            field=models.FloatField(default=0.0, verbose_name='Numeric Score'),
        ),
    ]
