# Generated by Django 6.0.1 on 2026-01-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='School Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='School Code')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Subject Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='schools.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='Student ID')),
                ('student_id_normalized', models.CharField(db_index=True, max_length=20, verbose_name='Normalized ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('grade', models.CharField(max_length=10, verbose_name='Grade')),
                ('section', models.CharField(max_length=10, verbose_name='Section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_students', to='schools.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Master Student',
                'verbose_name_plural': 'Master Students',
                'ordering': ['grade', 'section', 'surname', 'name'],
                'unique_together': {('school', 'student_id')},
            },
        ),
    ]
