# Generated by Django 6.0.1 on 2026-01-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='School Logo'),
        ),
    ]
